version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: documind_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=documind
    ports:
      - "5432:5432"
    volumes:
      - documind_postgres_data:/var/lib/postgresql/data

volumes:
  documind_postgres_data:
