version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: indicio_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=indicio
    ports:
      - "5432:5432"
    volumes:
      - indicio_postgres_data:/var/lib/postgresql/data

volumes:
  indicio_postgres_data:
